### ISSUE TITLE
[Feature] - simple miranum github template

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum-connect#166]
- [x] Description created
- [x] Reviewed by peer: @Hafflgav 
- [ ] Prioritised

# Description

The objective of this issue is to create a simplified GitHub template for users looking to start a new project using Miranum. This template should be structured to facilitate an easy-to-follow, beginner-friendly initiation to the Miranum ecosystem, focusing on the key features of Miranum Connect - creating a Worker, correlating a message, and starting a process.

## Sub-Tasks
 
```[tasklist]
### Tasks
- [x] **Structure the template**
- [x] **Creating a worker**
- [x] **Correlate a message**
- [x] **Start a process**
- [x] **Documentation**: Write a README (don't forget to mention in miranum-docs)
```

**Comment by rami-nk** [comment]
@Hafflgav The hardest of all tasks is ofc the naming. Which one would you prefer? 
- miranum-connect-starter-template
- miranum-connect-basic-template
- miranum-connect-quickstart-template
- simple-miranum-connect-template
- miranum-connect-template-basic

**Comment by Hafflgav** [comment]
> @Hafflgav The hardest of all tasks is ofc the naming. Which one would you prefer?
> 
> * miranum-connect-starter-template
> * miranum-connect-basic-template
> * miranum-connect-quickstart-template
> * simple-miranum-connect-template
> * miranum-connect-template-basic

@rami-nk, I am in favour of: 
* miranum-connect-basic-template
